function countries() {
    return {
        "low": ["Afghanistan", "Guinea", "Rwanda", "Benin", "Guinea-Bissau", "Senegal", "Burkina Faso", "Haiti", "Sierra Leone", "Burundi", "Korea, Dem. People's Rep.", "Somalia", "Central African Republic", "Liberia", "South Sudan", "Chad", "Madagascar", "Tanzania", "Comoros", "Malawi", "Togo", "Congo, Dem. Rep", "Mali", "Uganda", "Eritrea", "Mozambique", "Zimbabwe", "Ethiopia", "Nepal", "Gambia, The", "Niger"],

        "low-middle": ["Angola", "Indonesia", "Philippines", "Armenia", "Jordan", "São Tomé and Principe", "Bangladesh", "Kenya", "Solomon Islands", "Bhutan", "Kiribati", "Sri Lanka", "Bolivia", "Kosovo", "Sudan", "Cabo Verde", "Kyrgyz Republic", "Swaziland", "Cambodia", "Lao PDR", "Syrian Arab Republic", "Cameroon", "Lesotho", "Tajikistan", "Congo, Rep.", "Mauritania", "Timor-Leste", "Côte d'Ivoire", "Micronesia, Fed. Sts.", "Tunisia", "Djibouti", "Moldova", "Ukraine", "Egypt, Arab Rep.", "Mongolia", "Uzbekistan", "El Salvador", "Morocco", "Vanuatu", "Georgia", "Myanmar", "Vietnam", "Ghana", "Nicaragua", "West Bank and Gaza", "Guatemala", "Nigeria", "Yemen, Rep.", "Honduras", "Pakistan", "Zambia", "India", "Papua New Guinea"],

        "upper-middle": ["Albania", "Ecuador", "Nauru", "Algeria", "Fiji", "Panama", "American Samoa", "Gabon", "Paraguay", "Argentina", "Grenada", "Peru", "Azerbaijan", "Guyana", "Romania", "Belarus", "Iran, Islamic Rep.", "Russian Federation", "Belize", "Iraq", "Samoa", "Bosnia and Herzegovina", "Jamaica", "Serbia", "Botswana", "Kazakhstan", "South Africa", "Brazil", "Lebanon", "St. Lucia", "Bulgaria", "Libya", "St. Vincent and the Grenadines", "China", "Macedonia, FYR", "Suriname", "Colombia", "Malaysia", "Thailand", "Costa Rica", "Maldives", "Tonga", "Croatia", "Marshall Islands", "Turkey", "Cuba", "Mauritius", "Turkmenistan", "Dominica", "Mexico", "Tuvalu", "Dominican Republic", "Montenegro", "Venezuela, RB", "Equatorial Guinea", "Namibia"],

        "high": ["Andorra", "Greece", "Poland", "Antigua and Barbuda", "Greenland", "Portugal", "Aruba", "Guam", "Puerto Rico", "Australia", "Hong Kong SAR, China", "Qatar", "Austria", "Hungary", "San Marino", "Bahamas, The", "Iceland", "Saudi Arabia", "Bahrain", "Ireland", "Seychelles", "Barbados", "Isle of Man", "Singapore", "Belgium", "Israel", "Sint Maarten (Dutch part)", "Bermuda", "Italy", "Slovak Republic", "British Virgin Islands", "Japan", "Slovenia", "Brunei Darussalam", "Korea, Rep.", "Spain", "Canada", "Kuwait", "St. Kitts and Nevis", "Cayman Islands", "Latvia", "St. Martin (French part)", "Channel Islands", "Liechtenstein", "Sweden", "Chile", "Lithuania", "Switzerland", "Curaçao", "Luxembourg", "Taiwan, China", "Cyprus", "Macao SAR, China", "Trinidad and Tobago", "Czech Republic", "Malta", "Turks and Caicos Islands", "Denmark", "Monaco", "United Arab Emirates", "Estonia", "Netherlands", "United Kingdom", "Faroe Islands", "New Caledonia", "United States", "Finland", "New Zealand", "Uruguay", "France", "Northern Mariana Islands", "Virgin Islands (U.S.)", "French Polynesia", "Norway", "Germany", "Oman", "Gibraltar", "Palau"]
    };
}